# These are supported funding model platforms

github: BitwiseThought
patreon: BitwiseThought
open_collective: # BitwiseThought
ko_fi: # BitwiseThought
tidelift: BitwiseThought
liberapay: BitwiseThought
issuehunt: BitwiseThought
otechie: BitwiseThought
